on:
  push:
    branches:
      - main
  workflow_dispatch:
permissions:
  contents: write
  pull-requests: write
name: build-dist
env:
  ACTION_NAME: release-please-action
jobs:
  build-and-pr:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 20
    - name: install
      run: npm ci
    - name: build
      run: npm run build
    - name: Create PR with dist
      uses: googleapis/code-suggester@v4
      with:
        command: pr
        upstream_repo: release-please-action
        upstream_owner: RuggeroVisintin
        description: Build dist
        title: "chore: build dist"
        message: "chore: build dist"
        labels: automated pr
        branch: build-dist
        force: true
        git_dir: .
        fork: false
      env:
        ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
